[package]
name = "unftp-auth-rest"
version = "0.1.0"
description = "An authenticator back-end for libunftp that consumes an HTTP API to authenticate"
authors = [
    "Agoston Horvath <ahorvath@bol.com>",
    "Dávid Kosztka <dkosztka@bol.com>",
    "Hannes de Jager <hdejager@bol.com>",
    "Rob klein Gunnewiek <rkleingunnewiek@bol.com>",
]
edition = "2018"
license = "Apache-2.0"
keywords = ["libunftp", "ftp", "ftps", "auth", "rest"]
categories = ["network-programming"]
documentation = "https://docs.rs/unftp-auth-rest"
homepage = "https://github.com/bolcom/libunftp/tree/master/crates/unftp-auth-rest"
repository = "https://github.com/bolcom/libunftp/tree/hannes/crates/unftp-auth-rest"
readme = "README.md"

[dependencies]
async-trait = "0.1.42"
hyper = { version = "0.14.4", features= ["client", "runtime", "stream", "http1"]}
hyper-rustls = { version = "0.22.1"}
libunftp = { version="0.17.0", path="../../"}
unftp-sbe-fs = { version="0.1", path="../unftp-sbe-fs"}
percent-encoding = { version = "2.1.0"}
regex = "1.4.3"
serde = { version = "1.0.123", features = ["derive"] }
serde_json = { version = "1.0.62"}
tokio = { version = "1.2.0", features = ["rt", "net", "sync", "io-util", "macros", "time", "fs"]}
tracing = "0.1.23"
tracing-attributes = "0.1.12"


[dev-dependencies]
pretty_env_logger = "0.4.0"